### ISSUE TITLE
use propertyToAttribute

### ISSUE THREAD

**Issue by srghma** [purescript-halogen/purescript-halogen-vdom#41]
seems like we can reuse it

https://github.com/elm/virtual-dom/blob/5a5bcf48720bc7d53461b3cd42a9f19f119c5503/src/Elm/Kernel/VirtualDom.server.js#L196-L201

I will think where

**Comment by natefaubion** [comment]
Can you clarify what you want to accomplish?

**Comment by srghma** [comment]
I have added these additional props to https://github.com/purescript-halogen/purescript-halogen-vdom-string-renderer/pull/9

in https://github.com/purescript-halogen/purescript-halogen-vdom-string-renderer/pull/9/commits/8d3d50bcd43f56b158c82c74cc0f8a2533e2533a

and also added https://github.com/purescript-halogen/purescript-halogen-vdom/pull/38/commits/50c315a1fdb2a547830a8ed49c9ea93fec1e6025
