### ISSUE TITLE
use List instead of Array for children of Elem and Keyed

### ISSUE THREAD

**Issue by srghma** [purescript-halogen/purescript-halogen-vdom#42]
Elm is using linked list as far as I know for expedient speed.

Is it?

https://github.com/elm/virtual-dom/blob/5a5bcf48720bc7d53461b3cd42a9f19f119c5503/src/Elm/Kernel/VirtualDom.server.js#L72-L75

what would it take? mixfix for purescript compiler like in agda to define `[]` for List?

**Comment by natefaubion** [comment]
Elm uses linked lists is because that's what list literal syntax in Elm creates. I don't think it has anything to do with speed. If anything it would probably be slower due to more allocations.

**Comment by srghma** [comment]
ah, ok then

**Comment by srghma** [comment]
tnx!
